'use strict';

/**
 * Makes the app searchable from the Android TV global search box, following
 * https://developer.android.com/training/tv/discovery/searchable
 *
 * Three things have to line up for that, and they are generated together here because
 * they all hinge on the app's package name, which the module they belong to has no way
 * to know:
 *
 *  - res/xml/searchable.xml, the searchable configuration. `searchSuggestAuthority`
 *    points the system at our provider, and `includeInGlobalSearch` is what offers the
 *    app to the global search box in the first place. A resource file cannot resolve
 *    the `${applicationId}` manifest placeholder, so the authority has to be written
 *    out literally.
 *  - the <provider> declaration for TvSearchSuggestionProvider, under that same
 *    authority. A mismatch between the two fails silently - global search simply never
 *    calls the provider - which is why neither is left to be maintained by hand.
 *  - a searchable activity. The system only reads a searchable configuration that some
 *    activity claims, so MainActivity declares it and takes ACTION_SEARCH, which also
 *    lets the launcher hand a query straight to the app (see ReactNativeTvSearchModule).
 *
 * The android directory is generated by prebuild and not checked in, so this runs on
 * every build rather than being a one-off edit.
 */

const { AndroidConfig, withAndroidManifest, withDangerousMod, withStringsXml } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const PROVIDER_NAME = 'expo.modules.tvsearch.TvSearchSuggestionProvider';

/** Suffix appended to the package name. Only this plugin decides it; the native side reads it back out of the manifest. */
const AUTHORITY_SUFFIX = '.search';

const SEARCHABLE_META_DATA = 'android.app.searchable';

const SEARCH_ACTION = 'android.intent.action.SEARCH';

const HINT_STRING = 'tv_search_hint';
const SETTINGS_DESCRIPTION_STRING = 'tv_search_settings_description';

/**
 * Kept in step with `MIN_QUERY_LENGTH` in TvSearchSuggestionProvider.kt. Below this the
 * system does not ask at all, which matters more than usual here: a short query matches
 * most of the catalogue and costs a full scrape to find that out.
 */
const SUGGEST_THRESHOLD = 2;

const getAuthority = (config) => `${config.android?.package ?? config.package}${AUTHORITY_SUFFIX}`;

const buildSearchableXml = (authority) => `<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by plugins/withTvSearchable.js, edits are overwritten on prebuild. -->
<searchable xmlns:android="http://schemas.android.com/apk/res/android"
    android:label="@string/app_name"
    android:hint="@string/${HINT_STRING}"
    android:searchSettingsDescription="@string/${SETTINGS_DESCRIPTION_STRING}"
    android:searchSuggestAuthority="${authority}"
    android:searchSuggestIntentAction="android.intent.action.VIEW"
    android:searchSuggestThreshold="${SUGGEST_THRESHOLD}"
    android:includeInGlobalSearch="true" />
`;

const withSearchableResource = (config) => withDangerousMod(config, [
  'android',
  async (modConfig) => {
    const searchableXmlPath = path.join(
      modConfig.modRequest.platformProjectRoot,
      'app/src/main/res/xml/searchable.xml'
    );

    await fs.promises.mkdir(path.dirname(searchableXmlPath), { recursive: true });
    await fs.promises.writeFile(searchableXmlPath, buildSearchableXml(getAuthority(modConfig)));

    return modConfig;
  },
]);

/**
 * The hint shown in the search box and the label under Settings > Search > Searchable
 * apps. Both are Android resources rather than app strings, so they are not part of the
 * in-app translations and stay in English.
 */
const withSearchableStrings = (config) => withStringsXml(config, (modConfig) => {
  modConfig.modResults = AndroidConfig.Strings.setStringItem(
    [
      { $: { name: HINT_STRING }, _: 'Search for films and series' },
      {
        $: { name: SETTINGS_DESCRIPTION_STRING },
        _: 'Films and series available in the app',
      },
    ],
    modConfig.modResults
  );

  return modConfig;
});

const withSearchableManifest = (config) => withAndroidManifest(config, (modConfig) => {
  const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(modConfig.modResults);
  const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(modConfig.modResults);
  const authority = getAuthority(modConfig);

  // rebuilt from scratch rather than patched, so a changed package name cannot leave
  // the previous authority behind next to the new one
  const providers = (mainApplication.provider ?? []).filter(
    (provider) => provider.$?.['android:name'] !== PROVIDER_NAME
  );

  mainApplication.provider = [
    ...providers,
    {
      $: {
        'android:name': PROVIDER_NAME,
        'android:authorities': authority,
        // search runs in another process, so it can only reach the provider if it is
        // exported
        'android:exported': 'true',
      },
      // NOTE: no `path-permission` gating reads on android.permission.GLOBAL_SEARCH.
      // That permission is signature|privileged, so requiring it admits the system
      // search app and nothing else - it locks out ATV Поиск, USearch on Ugoos and
      // every third-party launcher, which is most of where a TV user actually searches.
      // What the provider hands out is a title, a year, a poster url and a deep link
      // into this app, none of it private. The one thing an unprotected provider does
      // give away is that any installed app can make this one run a search, so keep the
      // work behind it cheap and the results public - which they are.
    },
  ];

  // the searchable configuration is only read from an activity that claims it
  const metaData = (mainActivity['meta-data'] ?? []).filter(
    (item) => item.$?.['android:name'] !== SEARCHABLE_META_DATA
  );

  mainActivity['meta-data'] = [
    ...metaData,
    {
      $: {
        'android:name': SEARCHABLE_META_DATA,
        'android:resource': '@xml/searchable',
      },
    },
  ];

  const intentFilters = (mainActivity['intent-filter'] ?? []).filter(
    (filter) => !filter.action?.some((action) => action.$?.['android:name'] === SEARCH_ACTION)
  );

  mainActivity['intent-filter'] = [
    ...intentFilters,
    {
      action: [{ $: { 'android:name': SEARCH_ACTION } }],
      category: [{ $: { 'android:name': 'android.intent.category.DEFAULT' } }],
    },
  ];

  // NOTE: `android.app.default_searchable` is deliberately not declared. It would make
  // KEYCODE_SEARCH inside the app open the framework's legacy SearchDialog - a phone
  // sized overlay - on top of the TV UI, in front of a search screen the app already
  // has and which is built for a remote. Nothing about being findable from the TV
  // search box needs it: the global search box reads the configuration off the
  // activity's own `android.app.searchable` meta-data above.

  return modConfig;
});

const withTvSearchable = (config) => withSearchableResource(
  withSearchableStrings(withSearchableManifest(config))
);

module.exports = withTvSearchable;
