package expo.modules.tvsearch

import android.app.SearchManager
import android.content.ContentProvider
import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.content.pm.PackageManager
import android.database.Cursor
import android.database.MatrixCursor
import android.net.Uri
import android.provider.BaseColumns

/**
 * Answers the Android TV global search box, following
 * https://developer.android.com/training/tv/discovery/searchable
 *
 * The system calls this on a binder thread for every query the user types or speaks,
 * in a process it may have started for the call alone, and it moves on if the answer
 * does not come back promptly. The search itself lives in JS and takes seconds (see
 * [TvSearchLiveQuery]), so waiting for it here would mean never being shown at all.
 *
 * So the answer is always immediate, out of [TvSearchStore], and possibly empty. The
 * live search is kicked off alongside it, and the returned cursor carries a
 * notification uri for the query it answered: when JS publishes results,
 * [ReactNativeTvSearchModule] notifies that uri, the search UI re-queries it, and the
 * real results take the place of whatever was shown. This is the ordinary contract for
 * a suggestion source backed by a network - `CursorAdapter` requeries on content
 * change - and it degrades sanely on a launcher that ignores the notification: the
 * results are simply there the next time the same thing is searched for.
 *
 * The provider is declared by plugins/withTvSearchable.js, which also writes the
 * searchable.xml pointing at it. It is read-only; nothing but the module writes here.
 */
class TvSearchSuggestionProvider : ContentProvider() {
  private val store: TvSearchStore
    get() = TvSearchStore.getInstance(requireNotNull(context) { "Provider has no context" })

  companion object {
    /**
     * Queries shorter than this are not searched. `android:searchSuggestThreshold` in
     * searchable.xml already keeps the system from asking, so this only covers a
     * caller that asks anyway - a one or two letter query matches most of the catalogue
     * and costs a full scrape to find that out.
     */
    private const val MIN_QUERY_LENGTH = 3

    /** Cards the search UI is offered for one query, if it does not ask for fewer. */
    private const val DEFAULT_LIMIT = 10

    /**
     * How long a query's results are reused before it is searched again. The cache is
     * there to fill the gap while the live search runs, not to serve stale listings, so
     * this is short - but long enough that backspacing over a letter and typing it
     * again does not re-scrape.
     */
    private const val RESULT_TTL_MS = 5L * 60 * 1000

    private val COLUMNS = arrayOf(
      BaseColumns._ID,
      SearchManager.SUGGEST_COLUMN_TEXT_1,
      SearchManager.SUGGEST_COLUMN_TEXT_2,
      SearchManager.SUGGEST_COLUMN_RESULT_CARD_IMAGE,
      SearchManager.SUGGEST_COLUMN_CONTENT_TYPE,
      SearchManager.SUGGEST_COLUMN_PRODUCTION_YEAR,
      SearchManager.SUGGEST_COLUMN_IS_LIVE,
      SearchManager.SUGGEST_COLUMN_INTENT_ACTION,
      SearchManager.SUGGEST_COLUMN_INTENT_DATA
    )

    /**
     * The authority this provider is registered under, read back from the manifest
     * rather than rebuilt from the package name - the manifest entry and searchable.xml
     * are both generated by the config plugin, and this way the module cannot drift
     * from whatever they agreed on.
     */
    fun findAuthority(context: Context): String? = try {
      context.packageManager
        .getPackageInfo(context.packageName, PackageManager.GET_PROVIDERS)
        .providers
        ?.firstOrNull { it.name == TvSearchSuggestionProvider::class.java.name }
        ?.authority
    } catch (e: PackageManager.NameNotFoundException) {
      null
    }

    /**
     * The uri a cursor for [queryKey] observes and that publishing results notifies.
     *
     * Deliberately not the uri that was queried: that one carries the raw query text and
     * a `limit` parameter, and a notification has to match exactly what the cursor
     * registered for. Both sides build the uri from the normalised key instead.
     */
    fun notificationUri(authority: String, queryKey: String): Uri = Uri.Builder()
      .scheme("content")
      .authority(authority)
      .appendPath(SearchManager.SUGGEST_URI_PATH_QUERY)
      .appendPath(queryKey)
      .build()
  }

  override fun onCreate(): Boolean = true

  override fun query(
    uri: Uri,
    projection: Array<out String>?,
    selection: String?,
    selectionArgs: Array<out String>?,
    sortOrder: String?
  ): Cursor? {
    val context = context ?: return null

    if (uri.pathSegments.firstOrNull() != SearchManager.SUGGEST_URI_PATH_QUERY) {
      return null
    }

    val cursor = MatrixCursor(COLUMNS)
    val store = store

    // the query text arrives as the last path segment, or in the selection arguments
    // when searchable.xml declares a `searchSuggestSelection` - ours does not, but a
    // caller building the uri by hand may still use that form
    val query = uri.pathSegments.getOrNull(1) ?: selectionArgs?.firstOrNull() ?: ""
    val queryKey = TvSearchStore.normalize(query)

    if (queryKey.length < MIN_QUERY_LENGTH || !store.isEnabled) {
      return cursor
    }

    val limit = uri.getQueryParameter("limit")?.toIntOrNull()?.takeIf { it > 0 } ?: DEFAULT_LIMIT

    store.readRows(queryKey, limit).forEachIndexed { index, row ->
      cursor.addRow(
        // spelled out: the row mixes ints, strings and nulls, and an inferred array
        // type would be their common supertype rather than the Any? the cursor takes
        arrayOf<Any?>(
          index,
          row.title,
          row.subtitle,
          row.posterUri,
          row.contentType,
          row.productionYear,
          0,
          Intent.ACTION_VIEW,
          row.intentData
        )
      )
    }

    val authority = findAuthority(context)

    if (authority != null) {
      cursor.setNotificationUri(context.contentResolver, notificationUri(authority, queryKey))
    }

    // nothing to gain from re-scraping a query that was just searched; the cursor above
    // already holds what it found
    if (!store.isFresh(queryKey, RESULT_TTL_MS)) {
      TvSearchLiveQuery.request(context, query.trim())
    }

    return cursor
  }

  override fun getType(uri: Uri): String? =
    if (uri.pathSegments.firstOrNull() == SearchManager.SUGGEST_URI_PATH_QUERY) {
      SearchManager.SUGGEST_MIME_TYPE
    } else {
      null
    }

  override fun insert(uri: Uri, values: ContentValues?): Uri? =
    throw UnsupportedOperationException("The tv search index is written through the native module")

  override fun update(
    uri: Uri,
    values: ContentValues?,
    selection: String?,
    selectionArgs: Array<out String>?
  ): Int = throw UnsupportedOperationException("The tv search index is written through the native module")

  override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int =
    throw UnsupportedOperationException("The tv search index is written through the native module")
}
