export const PLAYER_VIDEO_SELECTOR_OVERLAY_ID = 'PLAYER_VIDEO_SELECTOR_OVERLAY_ID';
export const SCROLL_EVENT_END_PADDING = 200;
export const SCHEDULE_OVERLAY_ID = 'SCHEDULE_OVERLAY_ID';
export const MINIMUM_SCHEDULE_ITEMS = 5;
export const COMMENTS_OVERLAY_ID = 'COMMENTS_OVERLAY_ID';
